export const articles = [
  {
    id: '1',
    title: 'How to Improve Your Skills in League of Legends',
    keyword: 'league of legends',
    traffic: '[23456/500]',
    wordCount: 4078,
    createdAt: '29 hours ago',
    status: 'published',
  },
  {
    id: '2',
    title: 'How to Master Last Hitting in League of Legends',
    keyword: 'league of legends',
    traffic: '[22345/500]',
    wordCount: 2480,
    createdAt: '25 hours ago',
    status: 'published',
  },
  {
    id: '3',
    title: '7 Tips for Better Teamplay in League of Legends',
    keyword: 'league of legends',
    traffic: '[23456/500]',
    wordCount: 2676,
    createdAt: '9 days ago',
    status: 'published',
  },
  {
    id: '4',
    title: 'Top Virtual Executive Assistant Services (2024)',
    keyword: 'virtual executive assistant',
    traffic: '[2500]',
    wordCount: 3408,
    createdAt: '1 Oct 24',
    status: 'published',
  },
  {
    id: '5',
    title: 'Unlimited Graphics Design Solutions',
    keyword: 'unlimited graphic design services',
    traffic: '[1700]',
    wordCount: 1783,
    createdAt: null,
    status: 'unfinished',
  },
  {
    id: '6',
    title: 'Top Amazon Placement Methods for Quick Access to Funds',
    keyword: 'amazon placement methods',
    traffic: '[3500]',
    wordCount: 2547,
    createdAt: null,
    status: 'scheduled',
  },
  {
    id: '7',
    title: 'Backlinks 101: What are backlinks and why they\'re important [Free samples]',
    keyword: 'backlinks',
    traffic: '[8100]',
    wordCount: 2280,
    createdAt: null,
    status: 'scheduled',
  },
  {
    id: '8',
    title: '7 Leading AI SEO Tools in 2024 [Ranked & Compared]',
    keyword: 'ai seo software',
    traffic: '[1600]',
    wordCount: 1543,
    createdAt: null,
    status: 'unfinished',
  },
  {
    id: '9',
    title: 'Unlimited Graphic Design Services You Can Rely On',
    keyword: 'unlimited graphic design services',
    traffic: '[1700]',
    wordCount: 1974,
    createdAt: null,
    status: 'unfinished',
  },
]; 